=== AlenaVP/JD2018-03-22/src/by/it/fando/jd02_07/Client.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT Clients (Client)+>
<!ELEMENT Client (ClientID, Email, Nickname, Password, Orders)>
<!ELEMENT ClientID (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Nickname (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Orders (Order)+>
<!ELEMENT Order (Description, Size, Price)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Size (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price currency PCDATA>

=== AlenaVP/JD2018-03-22/src/by/it/fando/jd02_07/Client+DTD.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Clients SYSTEM "Client.dtd">
<Clients>
    <Client>
        <ClientID>1</ClientID>
        <Email>abc@mail.ru</Email>
        <Nickname>Andrew</Nickname>
        <Password>qwer</Password>
        <Orders>
            <Order>
                <Description>Пицца</Description>
                <Size>Маленькая</Size>
                <Price currency="р.">10</Price>
            </Order>
            <Order>
                <Description>Пицца</Description>
                <Size>Средняя</Size>
                <Price currency="р.">20</Price>
            </Order>
        </Orders>
    </Client>

    <Client>
        <ClientID>2</ClientID>
        <Email>def@gmail.com</Email>
        <Nickname>Sergey</Nickname>
        <Password>asdf</Password>
        <Orders>
            <Order>
                <Description>Пицца</Description>
                <Size>Большая</Size>
                <Price currency="р.">30</Price>
            </Order>
        </Orders>
    </Client>
</Clients>
