=== AlenaVP/JD2018-03-22/src/by/it/fando/jd02_07/Client.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://it-academy.by/fando"
        xmlns:tns="http://it-academy.by/fando"
        elementFormDefault="qualified">
    <element name="Clients">
        <complexType>
            <sequence>
                <element name="Client"
                         type="tns:Client"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>

    <complexType name="Client">
        <sequence>
            <element name="ClientID" type="int"/>
            <element name="Email" type="string"/>
            <element name="Nickname" type="string"/>
            <element name="Password" type="string"/>
            <element name="Orders" type="tns:Orders"/>
        </sequence>
    </complexType>

    <complexType name="Orders">
        <sequence>
            <element name="Order"
                     type="tns:Order"
                     maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Order">
        <sequence>
            <element name="Description" type="string"/>
            <element name="Size" type="string"/>
            <element name="Price" type="tns:Price"/>
        </sequence>
    </complexType>

    <complexType name="Price">
        <simpleContent>
            <extension base="string">
                <attribute name="currency" type="string" use="required"/>
            </extension>
        </simpleContent>
    </complexType>

</schema>

=== AlenaVP/JD2018-03-22/src/by/it/fando/jd02_07/Client+XSD.xml
<?xml version="1.0" encoding="utf-8" ?>
<Clients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://it-academy.by/fando"
         xsi:schemaLocation="http://it-academy.by/fando Client.xsd">
    <Client>
        <ClientID>1</ClientID>
        <Email>abc@mail.ru</Email>
        <Nickname>Andrew</Nickname>
        <Password>qwer</Password>
        <Orders>
            <Order>
                <Description>Пицца 1</Description>
                <Size>Маленькая</Size>
                <Price currency="р.">10</Price>
            </Order>
            <Order>
                <Description>Пицца 2</Description>
                <Size>Средняя</Size>
                <Price currency="р.">20</Price>
            </Order>
        </Orders>
    </Client>

    <Client>
        <ClientID>2</ClientID>
        <Email>def@gmail.com</Email>
        <Nickname>Sergey</Nickname>
        <Password>asdf</Password>
        <Orders>
            <Order>
                <Description>Пицца 3</Description>
                <Size>Большая</Size>
                <Price currency="р.">30</Price>
            </Order>
        </Orders>
    </Client>
</Clients>
